### ISSUE TITLE
Live captioning

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#11]
Inspired by chats with @AnnaGerber, we should look into whether we can do live captioning for our talks. Why?

* Up to 20% of people in the United States have some degree of hearing loss.
* Captioned English is much more accessible to speakers of other languages than spoken English alone.
* Our videos will already have caption transcripts after the event which we can put online without effort

We should work out if it's feasible, what the costs are, then find a sponsor willing to make this happen.

# Options
* http://www.whitecoatcaptioning.com/ has been used by some other events with success
* I've asked Morgan from the accessibility meetup who he uses
* Does anyone have any other recommendations?

# Questions
- [ ] Does koonjewarre have a landline and can we reserve use of it to run an audio feed to an external captioning service? (presuming we'll use 4G for the general use wifi, as per previous camps?)
- [ ] Do we have a TV available at the venue to display captions on?

If we can confirm these, then we can proceed to get some quotes.

**Comment by AshKyd** [comment]
@garrows can you have a peek at these questions, or point me at someone who can answer 'em? :)

**Comment by mcne65** [comment]
I would definitely love this as I have a hearing loss myself and am based in Australia! Can you tell me what can be done?

**Comment by AshKyd** [comment]
@mcne65 Just waiting on @garrows or someone else who might know the answer to the technical questions above.

If it's technically do-able, then we can get some prices and hopefully find a sponsor willing to make it happen.

**Comment by MauriceButler** [comment]
koonjewarre has a landline, whether we can tie it up or not I am not sure, we would have to contact the venue and ask.

If a landline is a necessity this locks us to being only able to caption one talk at a time?

**Comment by AshKyd** [comment]
> If a landline is a necessity this locks us to being only able to caption one talk at a time?

Sounds about right.

At this stage we're looking at having just the two streams; a talk stream and a workshop stream. I figure we can caption talks at the least, but probably do the intro/outro sessions as well.

**Comment by AshKyd** [comment]
I've emailed off asking for a quote based on the timetable work in #31, will see what they say

**Comment by mcne65** [comment]
What have they said for this particular issue?

**Comment by AshKyd** [comment]
I have a quote for around $3500. We're hamstrung on budget at the moment so can't make any decisions yet.

**Comment by AshKyd** [comment]
From what @gupta-kartik said, they don't have landline internet, so any captioning would be in contention with the regular Internet which isn't good enough to do anything with. Unfortunately I don't think this one is viable.

If anyone has any other suggestions for how we could make this work with these limitations, please let me know.
