### ISSUE TITLE
Projector Hire Koonjewarre

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#14]
Need to get quotes for Projector Hire from 10-13th August at Koonjewarre Camp, Gold Coast. We require:

- [ ] 3x projector + screen
- [ ] 3x sets of dongles (USBC➡HDMI, MiniDP➡HDMI)
- [ ] 3x microphone + speaker + amp
- [ ] delivery + setup

**Comment by thissophie** [comment]
@gupta-kartik does the venue provide PA equipment? In the past we’ve gone with getting the PA & projector gear from the same vendor. 

For reference last year we had:
3x projectors (two talks + workshop room) with 10M HDMI cables
3x 100” screens
3x microphones
3x speakers with built in amps

**Comment by AshKyd** [comment]
Throwing it out there, Koonjewarre is always a very bright venue and the projector is real difficult to see in the main presentation area.

* Would one or more TVs be easier to make out what's going on?
* OR should we consider sourcing some makeshift blackout blinds?

**Comment by AshKyd** [comment]
@MauriceButler you mentioned you were keen to help out with this one. Would you be able to help get us a quote for these items?

**Comment by MauriceButler** [comment]
:+1: been hunting for the previous supplier but no luck so far, will start the search for one.

**Comment by MauriceButler** [comment]
FYI, requests put out to 5 different suppliers, 1 has come back on Friday and said can do and will come back with pricing this week...

If I dont hear back from others Ill do another round requests.

**Comment by MauriceButler** [comment]
OK first actual quote back attached. These people were actually very responsive, asked about the needs and were very helpful.

Additionally, they have quoted an alternative to the 6’ Screen and Projector a 65” LCD Panel at a cost of $400.00 pls GST each.

They can also provide someone to sit there all day and run the equipment but I figured we could handle that ourselves?

~[CampJS AV C050654-00001Q-V001.pdf](https://github.com/campjs/campjs-ix/files/2113293/CampJS.AV.C050654-00001Q-V001.pdf)~

Updated Quote to get closer to budget, limited to 2 screens and projectors and we pickup and return though.
[CampJS AV C050654-00001Q-V002.pdf](https://github.com/campjs/campjs-ix/files/2135815/CampJS.AV.C050654-00001Q-V002.pdf)

**Comment by gupta-kartik** [comment]
Thanks for that @MauriceButler but we wont be able to spend that kind of money for the av hire. We were going off of the quote from last year (CampJS VIII) here https://github.com/campjs/campjs-viii/blob/master/org/quotes/av-hire.pdf

**Comment by gupta-kartik** [comment]
We can organise the pick up and delivery to save some cash incase it's expensive

**Comment by MauriceButler** [comment]
:+1: this is just first one to respond Ill add the others as they come in.

**Comment by MauriceButler** [comment]
~Just waiting on confirmation if this is total cost or each pricing ($1155 vs $3465)~

```
Hire costs for the following equipment from the 10 to 13th August including delivery and collection are

3 x Projectors (full HD)  $525
3 x 100” Screens  $150
3 x Self-Powered Speakers $225
3x USBC -> HDMI and Mini DP -> HDMI adaptors $30
3 x Wireless Mics  $225
delivery and pickup $300

Total $1455

Murray Coote -> sales@projectorhire.com.au 
```

**Comment by MauriceButler** [comment]
So it seems no one else could even be bothered to return the initial inquiry.

At this point these are the 2 options we have.

I still dont have a confirmation on if projector hire is each or total so I will case that again.

I will go back to microhire and see what they can do for around the $1k mark

**Comment by MauriceButler** [comment]
Updated the above comments. seems to me projectorhire.com.au wins 

@gupta-kartik @AshKyd someone want to take it from here and book + funds etc ?

**Comment by gupta-kartik** [comment]
Thanks so much for that @MauriceButler 
Do you have an email thread you could cc me on or forward it to me, and I can take it from there
kartik@campjs.com

**Comment by MauriceButler** [comment]
:+1: done

**Comment by iamkevinv** [comment]
Having only just landed here... for what it's worth, myself and the wife transported AV gear for the camp back in Oct 2014.
Sourced from Velvet Systems, Glenn Marshall (technical director av division - glenn@velvetsystems.com), 2/70 Lavarack Ave, Eagle Farm QLD 4009.

Original text from Glenn's quote was:

> We have the following projectors & screens available for this weekend:
> 
> 1 x Optoma (Full HD) 3000 lumens projector (HDMI + VGA inputs)
> 1 x Sanyo (XGA) 3500 lumens projector (VGA input only)
> 1 x Planar (XGA) 3000 lumens projector (VGA input only) 
>  
> 1 x 1.8m x 1.8m Tripod screen
> 2 x 2.0m x 1.5m Tripod screens
>  
> 2 x mini DisplayPort to VGA adapters 
> 1 x mini DisplayPort to HDMI adapter 
>  
> Pickup from our office:   Thursday 30 Oct 2014 (afternoon) 
> Drop back to our office:  Monday 3 Nov 2014 (anytime 9-5) 
>  
> Total price:         $ 297 inc GST. 
>  

I also have the original invoice from CampJS melb circa June 2015 for 5 projectors, 5 100" screens and delivery. Total exactly $600 from Ecoheart Pty LTD. (Just mentioned here for posterity).
