### ISSUE TITLE
Heater Hire Koonjewarre 

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#15]
Need quotes on Heater Hire for Koonjewarre for 10-13 August. About 7-10 Heaters should be fine.

**Comment by AshKyd** [comment]
Not really sure where these are going to go, actually. It's a grassy hill, so we're not going to be able to have standing heaters. Having resently visited the venue, what are your current thoughts @gupta-kartik?

**Comment by AnnaGerber** [comment]
I don't recall having standing heaters at Koonjewarre before (it is not as cold as the Melbourne venue, and the talks are indoors).

**Comment by AshKyd** [comment]
In that case I'm going to close this one for now. Let's reopen it if necessary.

**Comment by gupta-kartik** [comment]
I can ask the guy at Koonjewarre if they have some heaters we could use?

**Comment by AshKyd** [comment]
Crap, I didn't have this on my list of questions to ask for some reason. I reckon we'll be fine without it unless anyone has major objections.

**Comment by gupta-kartik** [comment]
Can we still email him to be sure? I'll add it to the list of questions to ask him in round 2.
