### ISSUE TITLE
Network Setup

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#16]
Network, intranet and internet setup for Koonjewarre for 10-13 August. Network should work across main hall, workshop room and one seminar room/area. Quotes wanted.

**Comment by developersteve** [comment]
I might know a company that could be interested in doing an in-kind sponsorship for internet and network things if thats an option

**Comment by AshKyd** [comment]
Oops, I duplicated this in #46 with a bit more info.
