### ISSUE TITLE
Name badges

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#17]
We are planning to have the following coloured lanyards (edited: 3.3.18)

* green for helpers / volunteers / organizers - 25
* orange for no photography please - 25
* black for everyone else - 140

We aim to have these sponsored by an organisation. Quotes needed. Last year, 200 same coloured lanyards and pouches cost us about $320.

**Comment by AnnaGerber** [comment]
Why no love for yellow? :)

Reflecting our discussion the other day, simplify to:

- green for helpers / volunteers / organizers
- orange for no photography please
- black for everyone else

**Comment by mcne65** [comment]
Have you started on this yet? Would love to help out in making them!

**Comment by gupta-kartik** [comment]
@mcne65 not yet but thanks a lot! I don't think we will be making them, just buying some in bulk and using them

**Comment by AshKyd** [comment]
Anna's suggestions sounds perfect. We should spin the name tags into this issue too, as it may make sense to get quotes from the same vendor.

Last camp the lanyards + pouches came in as  $318.50. I propose this time around we go with cardboard nametags to reduce plastic waste if possible. Not sure how if at all this will affect the cost.

Do we usually get the nametags printed? What's the opinion on giving the nametags an artwork/colour treatment [same as the website](http://ix.campjs.com/)?

**Comment by AnnaGerber** [comment]
Things that have been done for badges in the past: 

- printed paper insert that went into a plastic sleeve (sometimes difficult to fit the insert into the sleeve)
- printed cardboard blanks matching the website art work with sharpies for writing own names / info with a hole punched in to suspend from lanyard (these were pretty nice but the badges tore off easily) see https://plus.google.com/photos/photo/103492205915294852888/5910321767081130258?sqid=106906604683614333625&ssid=25afd2ec-bc92-4d32-963e-30e094fe7780
- custom playing cards with CampJS artwork on one side and other designs e.g. yetis on the other that went into a sleeve - also wrote on them using sharpies (the cards weren't very big - was difficult to fit name around the existing artwork on the cards)

Looking through previous photos, a lot of people don't bother with wearing lanyards - do we need them at all? Maybe another option would be to make custom button badges that would serve as swag as well as name/photo preference badges - the inside of the badges are just paper - could print something using similar artwork to the website but have different templates for photography preferences etc that people could write their names etc onto before pressing the badge. (I have a badge press - only takes a few seconds to make each badge and the badge hardware can be bought in bulk and cost around 40c per badge).

**Comment by AnnaGerber** [comment]
After discussion (in person) the badges instead of lanyards idea has traction. We can also make smaller badges as swag / a fun activity. What we'll need:

1. Prepare campsite artwork for the badges - the badge sizes are 58mm for the name badges and 25mm diameter for the souvenir badges. The name badge artwork should have plenty of clear space for people to write their name / social handle / job title etc (people can write what they want in this space). Possibly in a few different designs e.g. day/night was suggested but, and we can either incorporate photography preference in the template or we could use stickers for that
2. Order additional badge hardware (I am on this)
3. Provide sharpies, stickers etc for customizing and writing names etc onto the badges
4. Have at least one volunteer on the badge press on the Friday night when people are arriving to help with making the name badges

**Comment by AshKyd** [comment]
To reiterate, we're looking for a volunteer on the badge press for Friday Night when people are arriving to help with making the name badges. Can anyone help out?

**Comment by AshKyd** [comment]
@AnnaGerber do you need me to help with any of this stuff?

**Comment by AnnaGerber** [comment]
Still need help with:

- finding volunteers who can help out on the badge press. 
- finalising templates for the badges

**Comment by gupta-kartik** [comment]
@AnnaGerber do we have anyway to distinguish photography and no photography with badges? do we make an additional badge for no-photography participants?

**Comment by Anaizing** [comment]
I've put my hand up to do the photography throughout the event, but I can also help out on the badge press too!

**Comment by AshKyd** [comment]
That sounds amazing, thanks a bunch.

**Comment by AnnaGerber** [comment]
Pics of the badges:
https://twitter.com/khuskhuslen/status/1027837691365183488
