### ISSUE TITLE
CampJS Badges

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#18]
Last year we had paper badges in plastic sleeves. This year we aim to do this a little differently. CrikenCon recently had small computing boards that came with assembly instructions, see image attached. These were made by https://greatscottgadgets.com/

We need ideas and if so quotes on 150-200 of these. 
![dwwav3ru8aayefh](https://user-images.githubusercontent.com/4622084/36666796-703d9c06-1b37-11e8-9892-8a33470f4ecc.jpg)

(Image by Anna Gerber)

**Comment by AnnaGerber** [comment]
I liked it when the CampJS badges were big cardboard things where we could write our names and whatever else we wanted like Twitter handle in large letters. Bonus points if there are a bunch of stickers and sharpies so you can customize them

Here are some examples of hardware badges: https://hackspace.raspberrypi.org/features/badgelife-the-art-of-the-conference-badge 
This article goes into their design: https://hackaday.com/2017/01/10/what-makes-the-perfect-hardware-badge/ 

But a PCB badge seems a bit derivative to me (and unlike the LAN tap which is likely to appeal to the CrikeyCon audience, is a hardware badge a good match for the CampJS audience? I predict lot of them would end up in the trash or as junk and not really being used).

**Comment by AshKyd** [comment]
I'm with Anna. Closing this one to combine this one with #17
