### ISSUE TITLE
CampJs Merchandise

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#19]
2017 we had CampJS blankets which cost about $4000. We need ideas on merchandise to include this year. This should be CampJS merchandise. Open to see if this could be sponsored i.e. can include CampJS logo + sponsor logo.

**Comment by garrows** [comment]
Last year there was a long discussion about shirts. Some wanted shirts, others didnt. We went with blankets instead (the limited shirts were from the year before). 

I propose the merch isn't included in the ticket this year which will make the tickets $20-$30 cheaper. 
Instead, we could setup an online store. Here is a good example https://www.redbubble.com/people/danvogt/shop

**Comment by AnnaGerber** [comment]
Socks were a popular option during last year's discussions too

**Comment by mcne65** [comment]
I would personally not go with anything at all - just stickers.

**Comment by gupta-kartik** [comment]
I like the idea of just having stickers and CampJS merchandise like Tshirts, socks for sale. We need a logo designer for this year too. I'll open an issue for that.

**Comment by AshKyd** [comment]
Then there's @AnnaGerber and @colingourlay seemed keen on screen printing a la JSConf. We'd need to come up with a screen-printable design + some budget to pay whoever we get to bring the equipment/run the show. Anyone want to look into what this would involve?

**Comment by AnnaGerber** [comment]
Another suggestion is DIY small button badges see #17

**Comment by AshKyd** [comment]
That sounds great. Unless anyone specifically wants to work on any other merch I'm going to close this one and continue the work in #17 :D
