### ISSUE TITLE
Buses and Transport

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#20]
2 or 3 buses from Gold Coast Airport (OOL) to Koonjewarre Afternoon and Evening on Friday 10th August and 2 or 3 buses back from Koonjewarre to OOL on Monday 13th August Morning.

**Comment by mcne65** [comment]
Apart from the buses arriving and departing for the number of people accommodated, how about also who would be driving up from other parts of Australia and if they would like to take guests in their car for that

**Comment by gupta-kartik** [comment]
That is a good idea @mcne65

**Comment by AshKyd** [comment]
from @mcne65:
> Why don't we ask participants though who are going on the bus if they would like to stop at Dan Murphy's for some wine and a supermarket/market area for some food before getting to campsite?

@mcne65: as you're interested in this would you be able to do up a schedule for the buses? Basically when they leave the airport, where and when they should stop, and what time they'll arrive at camp? You can probably find what we've done for previous camps, but this time I think it will be a different route because one of the roads is closed. So maybe use Google Maps for time estimates.

**Comment by mcne65** [comment]
Only problem is I am not familiar with Gold Coast roads!

**Comment by AshKyd** [comment]
Same here. I figured we'd use Google Maps :)

**Comment by mcne65** [comment]
Alright then, I'll have a look when I get the chance. Sorry it has been hectic in the last month or so, so haven't had much of an opportunity to gather more information.

**Comment by AshKyd** [comment]
Modified from the previous GC camp:

FROM Coolangatta Airport
BUS 1 - 48 seater

 14:00 - Pick up Airport
 14:45 - Pick up Varsity Lakes Train Station
~15:00 - Stop off at Dan Murphy's Robina (tbd in #47)
~16:30 - Koonjewarra (~50 mins on Google Maps)

BUS 2 - 28 seater

 17:00 - Pick up Airport
 17:45 - Pick up Varsity Lakes Train Station
~18:00 - Stop off at Dan Murphy's Robina (tbd in #47)
~19:30 - Koonjewarra (~50 mins on Google Maps)

FROM Koonjewarre Retreat (Monday 23 November 2015)

BUS 1 - 28 Seater
 08:00 - Pick up Koonjewarra
~09:30 - Drop off Varsity Lakes Train Station
~10:00 - Drop off Coolangatta Airport

BUS 2 - 48 Seater
 10:30 - Pick up Koonjewarre
~12:00 - Drop off Varsity Lakes Train Station
~12:30 - Drop off Coolangatta Airport

Providing there were no dramas last time around, let's go with this schedule. Edit: is this going to be enough seating?

**Comment by AshKyd** [comment]
Here's a draft schedule. I've sent this to a few folks for organizing flights, so we'll need to make sure the airport and train connections don't change. http://ix.campjs.com/schedule/

**Comment by gupta-kartik** [comment]
Quotes received. 2 buses, both 48 seaters according to above plan. Paying for them now.

**Comment by gupta-kartik** [comment]
Booked
