### ISSUE TITLE
Photography/Videography

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#21]
We need 2 photographers and videographers for the weekend and post image processing help too.

**Comment by justindra** [comment]
I can possibly help with the photography side of things.

**Comment by gupta-kartik** [comment]
@justindra Hi, Are you still available for this. Apologies for the late reply?

**Comment by justindra** [comment]
@gupta-kartik Sorry completely forgot about this as well. Not sure if I'll be able to be there the whole weekend anymore. When do you need me to get back to you by to confirm?

**Comment by gupta-kartik** [comment]
Soon would be good @justindra 

We can support you in case you want to do just photography

**Comment by AshKyd** [comment]
I think we should bring in some folks to do another promo video for future camp(s).

**Comment by Anaizing** [comment]
Hi! I can also do photography if you need a second person. I have all the photography equipment required. And I am available to attend the entire event.

😄 📸 👌

**Comment by gupta-kartik** [comment]
@Anaizing Thanks for that! Can you please send me an email on kartik@campjs.com and I can get this sorted for you. Do you have some previous work examples?

**Comment by gupta-kartik** [comment]
https://www.airtasker.com/my-tasks/photography-and-videography-for-2-day-tech-retreat-10858923/review-offers/photography-and-videography-for-2-day-tech-retreat-10858923/8009327/ 

For the professional Videography

**Comment by iamkevinv** [comment]
Last i heard here, the airtasked videographers have basically taken the money and run, delivering no footage from the event. Can we take action against them @gupta-kartik, or in the very least recover the raw footage if they are unwilling to do further work on cutting/final processing?
For some of us, the recording of the speaking we did has a tangible impact on whether we can continue to argue to support such events,future marketing of the event, our employers, and future technical directions we have been presenting.

**Comment by iamkevinv** [comment]
@gupta-kartik - have you made any progress on getting lawyers to send a threatening letter to the videographers? There's still a need to recover the footage to justify sponsorships again and such for this upcoming camp. Even if they handed over raw footage.
