### ISSUE TITLE
Childcare

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#25]
This issue is a stub, feel free to add to it. :)

Requires
- [ ] Quotes (previous camps estimated 8-10 kids would would cost $1138 for carers + activities)
- [ ] Sponsorship
- [ ] Promotion so folks know it's a thing
- [ ] Some way of indicating whether this is required as part of the ticketing

**Comment by mcne65** [comment]
Does the camp organise this at all?

**Comment by AshKyd** [comment]
Yes.

**Comment by cathylill** [comment]
Last year the best quote was from http://abrachild.com.au/events-mobile-pop-up-creche/. The pricing structure was a bit complicated but it was something like $40 per hour per carer (min 2 carers for 4hrs) + 2hrs per carer per day for setup / tear down + $15 per child per day for activity supplies. They required an indoors space with access to a sink with hot water, microwave and change table. Number of carers depends on the age of the kids as they need more carers for younger kids and babies. Lmk if you want me to dig up the email, they responded pretty promptly to an email enquiry.

**Comment by AshKyd** [comment]
Thanks @cathylill, that's great . That raises a good point as to _where_ this space will be, I presume we can set an area aside in the farmhouse.

I've gone back to your work on [CampJS VIII](https://github.com/campjs/campjs-viii/issues/18) which is also awesome. Wondering, was the 10 AM-12 PM + 2PM -4 PM childcare proposal based around when talks were running?

**Comment by cathylill** [comment]
@AshKyd yep I think it was just a way to spread out the 4hrs to keep costs down, so we weren't paying for childcare during lunch just while (some) talks we're on. It never went ahead in the end though so don't know if it would have worked well. It got pretty complicated working out how to price kids and partner tix and accom too, not sure if anyone ended up taking kids, I couldn't make it as it turned out.

**Comment by AshKyd** [comment]
There is appropriate space in The Farmhouse for this, according to David of Koonjewarre.
