### ISSUE TITLE
General diversity & inclusiveness initiatives (tbd)

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#26]
At the moment this is the "misc" issue for items that don't have their own issue yet. If you'd like to help make any of these happen, please get in touch.

See the [diversity and inclusiveness](https://github.com/campjs/campjs-ix/labels/diversity%20%26%20inclusiveness) label for the issues that have been broken out already.

The remainder of the things we want to look into this time around:

* Non-tech activities for folks who want some time out (hiking, photowalk, knitting/making, drone fights ?? etc)
* Diversity tickets for marginalized groups
* * probably via sponsorship
* * reach out to appropriate groups
* * check out https://diversitytickets.org/ - is it appropriate? Experiences?
* student & first timer discounts
* gender neutral bathrooms & improved signage #39 #40 
* personal hygiene essentials provided (work out what we need and make that known) #34 
* better choices in accommodation #37 
* * women's, couples/mixed, families dorms + info on off-site accommodation.
* * [Documented on the site](http://ix.campjs.com/the-camp/accommodation/) but we may need to revise it based on feedback, make sure it's all workable, and include it in the ticketing.
* Designated quiet/escape space for folks who need some time out - can we use The Cottage, or a space in The Farmhouse? #50

As always, if there's something missing or something you'd like to discuss, please get in touch (whichever is more comfortable, here or directly).

**Comment by mcne65** [comment]
Could we also have people with disabilities available also who would like to come along? And the designated quiet space sounds like it's for this market.

**Comment by AshKyd** [comment]
@mcne65 For sure. We've got an issue open over in #27 to get in touch with the venue for some more info concerning the physical accessibility of the camp, because I want to make sure we can actually accommodate folks properly. Is that kinda what you're thinking?

**Comment by mcne65** [comment]
Definitely! Also if there is cabins which are less noisy for those folks who have sensory issues if so...
