### ISSUE TITLE
Accessibility research & statement

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#27]
We need to be clear about what CampJS can and can't provide.

For instance, we may need to provide accessible accommodation in the dormitory units (near the hall) as the family units (downstairs) aren't really accessible.

Some things we need to do:
- [ ] check what the folks at koonjewarre already have in terms of accessibility info
- [ ] check the gradient of the outdoor ramp
- [ ] find out where there are stairs, and consider them off-limits to primary activities
- [ ] check what we can do to make the farmhouse accessible (the gravel may not work for wheelchairs unless we lay something down, are there stairs?)
- [ ] are there accessible bathrooms/showers near the main hall?
- [ ] is the accommodation suitable for folks in wheelchairs?
- [x] Check whether we can provide live captions (in #11)
- [x] Find a checklist or resource online to augment this list because I don't know what I'm looking for, for the most part

**Comment by AnnaGerber** [comment]
This guide looks comprehensive: http://www.meetingsevents.com.au/downloads/Accessible_Events_Guide.pdf

**Comment by AshKyd** [comment]
Thanks @AnnaGerber that's awesome. :)

**Comment by AshKyd** [comment]
@garrows Here's some suggested things to check for when you get in touch with the venue.

**Comment by mcne65** [comment]
Apart from live captioning, will there be a speaker/microphone in the room for the talks for accessibility also? And will there be a time out space?

**Comment by AshKyd** [comment]
1. yes.
2. that's the intention. It's listed in #26 but I don't know the space well enough to say _where_. Anna has suggested there's space upstairs. Created an issue in #50

**Comment by AshKyd** [comment]
Re accessibility, David says the venue is wheelchair accessible, and service dogs are welcome. The Farmhouse has accessible shower and toilet facilities.

My take is that it's really only _partially_ accessible because
1. The ramp from downstairs to upstairs is quite steep, and according to David wheelchairs "would need to be pushed".
2. The Farmhouse is on the other side of a gravel driveway, so you do need to go offroad to get there which might not be appropriate for everyone.

Next steps, I'ma write up a statement outlining what we've got and put that on the site. Better late than never.
