### ISSUE TITLE
Draft schedule

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#31]
Work out a skeleton schedule so we know how many speakers we can fit, etc.

This should have:

* bus travel
* intro speaking
* meals
* 2 tracks: talks & workshops
* anything else?

**Comment by AnnaGerber** [comment]
In case it helps, draft schedule from the last camp is here: https://docs.google.com/document/d/1jbmEzycn89KeOWKYO7IU1SUR7vKvk40Zw1FArb_u_cg/edit

**Comment by AshKyd** [comment]
That's rad, thanks Anna.

I've [made a start on a schedule here](https://docs.google.com/spreadsheets/d/1KGAqCawT_vhkLJWdiAsu7WtaoA86eIVd4XPD4kvmqxc/edit#gid=0) but I'm mainly focusing on talks right now so we know what we need to budget. Based it loosely on the CSSConf schedule, and also put in a fair whack of time for lightning talks at the end.

Hopefully in this format someone can use the data to build a sweet calendar widget/web app.
