### ISSUE TITLE
Shopping list

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#34]
This is going to need to be a Coles/Woolworths order in advance. Items taken from [shopping list from previous camp](https://github.com/campjs/campjs-viii/issues/95).

Items denoted ❓ indicate that we bought these last time and can we reuse them?

Food & Snacks
--------------------
- [ ] Juice
- [ ] Flavoured milk + soy milk
- [ ] Ginger beer
- [ ] Fruit
- [ ] Nuts
- [ ] Bottled water
- [ ] 

We also need to consider items required for childcare in #25. As per the article cathylill posted last camp, we need to consider [healthy and baby food options](https://medium.com/leaky-abstractions/conference-childcare-part-1-helpful-thoughts-for-conference-organizers-203d2b34df5b) and may want to consult with the parents taking up the childcare offer.

Bathroom & necessities
-------------------------------
- [ ] ❓  Towels (~$8 each from Target)
- [ ] Soap
- [ ] Toothbrushes
- [ ] Toothpaste
- [ ] Deodorant
- [ ] Shampoo
- [ ] Pads
- [ ] Tampons
- [ ] Baby wipes

Misc
-------
- [ ] Blu tac (for posting signage)
- [ ] Cups
- [ ] Wine cups
- [ ] Tea
- [ ] Thick garbage bags (not budget ones) so they don't break all the time
- [ ] Glow sticks
- [x] ❓ First aid kit?
- [ ] ❓ Bottle openers
- [ ] ❓ USB sticks
- [ ] Sticky labels for drinks/posessions
- [ ] Sharpies (2 for emergencies)

**Comment by mcne65** [comment]
Why don't we ask participants though who are going on the bus if they would like to stop at Dan Murphy's for some wine and a supermarket/market area for some food before getting to campsite? Also bring out rubbish bins if possible. I would bring extra stuff just in case, mainly sweets/chocolate/candies at bulk .

**Comment by AshKyd** [comment]
Yup. This is a (stub) shopping list for the organizers, I've added your other comment to the buses issue.

**Comment by AshKyd** [comment]
Assigning this to Garrows to work out how much of this stuff we still have from last camp and remove it from the list if necessary.
