### ISSUE TITLE
Speaker guide

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#35]
Some notes:

* Consider white on black slides to increase contrast on the projected screen.

From last time (thanks @AnnaGerber):

Tips for preparing slides and other presentation content:

1. Ensure your presentation conforms with the Code of Conduct
1. Avoid putting text too close to the edges (projectors sometimes cut off the edges / top / bottom)
1. Make sure you use text that is large enough to read from a distance (e.g. 18 pt or larger)
1. Remember that some colors may not show up well on the projector - projectors often have poor contrast during the day. Please also consider people who are colorblind when selecting colors for slides.
1. Internet access may not be available so please have a back up plan (e.g. take screenshots / video) rather than relying on live demos involving network access
1. Consider checking your slides with http://slidelint.net/ to avoid common pitfalls

**Comment by mcne65** [comment]
There are just too many speakers! How about some of them to be turned into a workshop and some for talks at same time?

**Comment by AnnaGerber** [comment]
I believe the intention for this camp is to schedule far fewer talks this camp than last one (i.e. a single track of talks only)
