### ISSUE TITLE
Code of Conduct training/workshop

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#36]
TBD so I remember to work on this

**Comment by mcne65** [comment]
I would be more than happy to host this part as I have knowledge in this area @garrows

**Comment by AshKyd** [comment]
Great. This is intended to introduce volunteers who have indicated they're willing to help out with enforcing the code of conduct. I'd love to use [this model](http://geekfeminism.wikia.com/wiki/Anti-harassment_policy_resources) because the resources are pretty great, but let me know what you think.

If you're offering, it would be great to formalize how to handle incidents, as well as come up with a presentation that we can go through with the volunteers prior to the event.
