### ISSUE TITLE
Accommodation types

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#37]
Previous camps have been separated by womens and mens dorms. This is somewhat exclusionary and we've had feedback that it can be a bit off-putting.

Should we change this to something like:
1. women's dorms
1. family dorms (for families, particularly with kids)
1. general, non-gendered dorms for anyone who doesn't want to take up one of the other two options

We obvs still offer:
* bring-a-tent
* off-site accommodation at a local b&b

Does this sound right? Got any opinions/recommendations?

**Comment by thissophie** [comment]
I think this is what happened at VIII, with the addition of a marked snorers cabin.
