### ISSUE TITLE
Gender neutral bathrooms

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#39]
For the purposes of gender-neutral bathrooms: does Koonjewarre have any toilets in the common areas, or are they all limited to the dorms?

If they're limited to the dorms, then this is a non-issue. But if we have any in shared spaces we should ensure we have gender-neutral bathrooms available.

**Comment by garrows** [comment]
They are in common areas plus some in the family dorms. 
We need signs to cover up the gendered signs though.
