### ISSUE TITLE
CampJS slide deck to attract more CFP

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-ix#4]
We need a short slide deck done up to send out to other meetups and groups to drum up more CFP.

Make sure it

1. Is short
2. Highlights diverse attendees in photos
3. Covers large range of talks (beginners, non-technical, etc)
4. Encourages first time speakers

**Comment by AshKyd** [comment]
Started work in a repo here: https://github.com/campjs/promo-meetup-resources
