### ISSUE TITLE
Signage

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#40]
We will need signage (printouts + blu tac, probably) for the following. Please add to the list if you can think of anything else that would benefit:

* Code of conduct info
* Maps of the venue
* Schedule (nice to have)
* Signs for on the doors of each dorm (#37) to indicate whether it's:
* * Women's dorms
* * non-gendered dorms
* * Family dorms
* * Snorer's dorms
* Bathroom signage (see #39)
* Signage for the childcare space + any rules (be considerate, no swears zone etc) (see #25)
* Time out space + rules (#50)

If anyone wants to have a crack at doing up a Google Doc of the various signage required so we can print out what we need closer to the date, that would be rad.

**Comment by mcne65** [comment]
What about something just for reminders on accessibility issues? Also will there be a camping area?

Thank you
Sirani McNeill

**Comment by margalit** [comment]
![image](https://user-images.githubusercontent.com/2268424/42988278-51cc9460-8c3f-11e8-878c-7f2f9162af5e.png)

I quickly knocked together a template here: https://docs.google.com/document/d/1B7YihTpoVO2x-5OIoeGrUK-DuAiK32RUiNZcQsRzKs0/edit?usp=sharing

If no-one else picks up this issue, I’ll fill out the above signage when I get a chance.

**Comment by AshKyd** [comment]
That looks awesome, thanks @margalit.

**Comment by margalit** [comment]
I have updated the above link to include signage for the following (an (x) marks a complete however I would appreciate someone checking over them):
- [x] Saturday Schedule
- [x] Sunday Schedule
- [x] Code of Conduct
- [x] Women’s Dorm
- [x] All-gender Dorm
- [x] Family Dorm
- [x] Snorer’s Dorm
- [x] All-gender Bathroom
- [x] Childcare Area
- [x] Camping Area
- [x] Quiet Space
- [x] Register Here (helpful for signing in)
- [x] CampJS Bus (figured this might be helpful for wayfinding at the airport)

## Instructions for adding new signage
[Open the public google document]( https://docs.google.com/document/d/1B7YihTpoVO2x-5OIoeGrUK-DuAiK32RUiNZcQsRzKs0/edit?usp=sharing)

The header and footer in the google doc are replicated on each page so to create a new one just insert a page break (`cmd` + `enter` / `ctrl` + `enter`) and use the type styles (Title, Heading 1 & Normal Text).

@AshKyd I was thinking we could add an emergency contact number to the header of all pieces of signage—do we have a designated person/number for that?

**Comment by margalit** [comment]
Schedules added as per http://ix.campjs.com/schedule/ August 1st.
