### ISSUE TITLE
Alcohol at camp (how to do?)

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#47]
This is a somewhat controversial issue as apparently the BYO drinks wasn't popular at the previous camp we tried it at. That said, we need to work out how this works. Previous camps we have had a bartender with a RSA provide drinks (#22), but I'm unclear what this achieved.

We need to work out whether/how we can legally serve drinks, and what kind of insurance we need to cover this.

**Comment by AshKyd** [comment]
When we spoke to the lawyers they suggested we may be able to _sell_ alcohol, and checking out the Queensland licensing info we can [apply for a permit](https://ablis.business.gov.au/service/queensland/community-liquor-permit/35388) (I don't think the exemptions apply for us, because we're a several day affair)

It's unclear whether we can provide free alcohol. @gupta-kartik @garrows do you remember what the response was to this? Do we know what other camps are doing? If not, I'm thinking it's worth spending some more lawyerly cash to definitively answer this question.

**Comment by mcne65** [comment]
The last Ruby on Rails camp I went to, we stopped at Dan Murphys for the alcohol to be refrigerated but it was for 18+ over only.

**Comment by AshKyd** [comment]
Kartik is going to chase this one up.

**Comment by AshKyd** [comment]
Crap, committed directly instead of making a PR. @gupta-kartik can you have a sneaky peek at that last commit and see if you agree with the sentiments?

**Comment by gupta-kartik** [comment]
Looks good @AshKyd

**Comment by AshKyd** [comment]
@gupta-kartik did you manage to clear this with legal?

**Comment by gupta-kartik** [comment]
Hey @AshKyd yes I did. I have sent you and @garrows their response via email. The long and short of it is, we can't provide or sell alcohol. Nothing is mentioned about BYO. Will chase them up to confirm BYO.

**Comment by AshKyd** [comment]
David at Koonjewarre says their insurance is fine for BYO.
