### ISSUE TITLE
Refrigeration

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#48]
We need to look into refrigeration + whether we need to hire fridges. Things to consider:

- [ ] Space for parents to safely store baby goods
- [ ] Space for attendees to store personal drinks/items
- [ ] Space to store free-for-all drinks provided by the camp

I know previous Koonjewarre camps we've had ice boxes outside which is fine for drinks, but not appropriate for baby stuff. Perhaps a hybrid approach?

**Comment by AshKyd** [comment]
Someone mentioned there was a mobile fridge trailer at a previous camp. @garrows do you have the detail?

**Comment by AshKyd** [comment]
Damon probably has these details.

**Comment by gupta-kartik** [comment]
Got quote for a 2 door commercial fridge.

**Comment by gupta-kartik** [comment]
Ordered.
