### ISSUE TITLE
Designated quiet/escape/time-out space

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#50]
This is something a few folks are keen on (me included), because sometimes you just need to get away from it all. Nothing set in stone yet, but could have:

* a comfortable place to lounge ^_^ (bean bags? yoga mats for folks who want to stretch out?)
* a screen with a stream of the talks (could be difficult, does someone have ideas or want to try and make this work?)
* Book swap? (Does the benefit of having reading material handy outweigh making this a non-time-out destination?)
* Other?
* * coloring books and pencils (inspired by DDD)

I'm really keen to know what folks think makes a good time-out space, or if anyone's experienced a good on at another conference.

Also need to find somewhere for this to go. Anna had a suggestion but need to clarify where it is.

**Comment by mcne65** [comment]
I'd be keen to host the arts and crafts part in this quiet space as well

**Comment by AshKyd** [comment]
Cool, can you please create an issue for the arts and crafts activity you're wanting to host so we know what it is & can make sure folks know about it?

**Comment by mcne65** [comment]
Alright I can take this onboard.
