### ISSUE TITLE
Talk review process

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#51]
This process is already underway, but including this issue to track that + log feedback.

From one participant:
> Suggestion for future review process - I'd recommend splitting the talk reviewing up rather than getting everyone to review all of the talks - e.g. 6 reviewers might do a third each.

**Comment by mcne65** [comment]
I have already done my part in it but I don't think anyone has had a look since it's only partially completed because didn't get a chance/time to look through everything properly. Please could you extend more time for folks also next time since this was a really long submission

**Comment by AshKyd** [comment]
Sorry @mcne65 we had to have the deadline because we need to get back to speakers (it's only 2 months away). I'm sure you saw, there were a _lot_ of good talks, so we're working out the final details now and I'm planning to email the speakers… when I have time to breathe :joy:

**Comment by mcne65** [comment]
I do know that but it didn't give me enough time to look at it like you just said and the emails to the speakers. Though I'd love to help you out on half of it if they are successful or not - let me know.

**Comment by AshKyd** [comment]
There's a lot that could have gone better with this process. I'm going to make a personal note to write up the successes & failures we had here.
