### ISSUE TITLE
Book swap

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#52]
In order to make the book swap a success this year it might help to have a bit of a campaign around it.

Would someone like to take ownership of this? This might involve things like: 

- [ ] Write a few pars explaining what the book swap is, how it usually works, and how to participate in it. We can add this to the website + send that out as part of the CampJS newsletter
- [ ] Maybe write a blog post about your experiences that we can post on the Medium blog?
- [ ] Other?

**Comment by mcne65** [comment]
Happy to help you but does not need to just to be only book swap only.

**Comment by AshKyd** [comment]
Fair point. I've invited you to the org so you can be assigned this issue. Thanks!
