### ISSUE TITLE
Streaming talks over the internal network

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#53]
A few folks have suggested streaming talks over the internal network, so that the hall downstairs and the time out space in #50 can enjoy the talks too.

I'm not sure how possible this is, but would anyone like to give it a shot?

**Comment by thissophie** [comment]
I'm up for helping make this happen.

Ideally we'd get a video feed from the camera that we are using to record the talks for consumption after the event, and also a video feed showing whatever is on the projector. Alternatively we can throw an extra camera that aims to capture the presenter and the projector screen and use that purely for an internal stream. 

From the camera / capture side I have all the equipment needed to make something that VLC could consume, suitable for showing on screens in other rooms.

**Comment by AshKyd** [comment]
Sounds awesome! Are you okay to take this one and run with it?

I know we'll have a projector downstairs, but if this is a go-er we will need to get a tv+compute in the quiet space in #14.

**Comment by thissophie** [comment]
:+1: 

I will do some testing to make sure it'll work, but I can bring a couple of small computers for that, so it'd just be tv & networking cable (but I know we'll have enough of that)
