### ISSUE TITLE
Arts and Craft Activities 

### ISSUE THREAD

**Issue by mcne65** [campjs/campjs-ix#54]
This may be hosted by Sirani or someone else in the designated quiet space

Would like to teach knitting, embroidery and card making. I am open to do let everyone do their different arts and crafts activities at the same time, just may need two more people to assist me depending on the number of people there are. I would like to run this ideally at lunchtime or at night

**Comment by AnnaGerber** [comment]
I would be happy to bring along some yarn from my stash for people who want to learn knitting / crochet
