### ISSUE TITLE
Ludlam Dare game jam

### ISSUE THREAD

**Issue by AnnaGerber** [campjs/campjs-ix#55]
From Nathan on the wealljs slack:

"The next Ludum Dare is on during CampJS so I thought it might be interesting to suggest it as a side activity" https://ldjam.com/

"Ludum Dare is one of the world's largest and longest running Game Jam events. Every 4 months, we challenge creators to make a game from scratch in a weekend."

It starts at 8am on the Saturday morning

Ideas to support this:

- Provide some getting started with JS game dev resources -  useful libraries, public domain or CC art or sound assets etc. Provide links in the comments on this issue and we can collate them into a page on the campjs intranet and make sure we have local copies
- Include shout out in the opening session on the Friday night so people are aware of the game jam and the rules
- Schedule game-related talks/content early in the program so people can apply it in the game game (maybe even on Friday night?)

**Comment by nathanhoad** [comment]
I'm happy to put together a list of resources, etc.

**Comment by nathanhoad** [comment]
I'll flesh out the some details about each thing but the list so far is:

# Engine

* Phaser

# Art

* Aseprite
* LibreSprite (free but old version of Aseprite)
* Piskel

# Level building

* Tiled
* OGMO

# Sound/Music

* BFXR
* GarageBand (plus Magical 8Bit Plugin?)

# Bundling/distribution

* Electron
* npm-icns (deprecated but still useful)

**Comment by iamkevinv** [comment]
Woot woot!
