### ISSUE TITLE
Campfire Jam

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#56]
Do you sing or play the ukulele / guitar/ kazoo? Do you want to learn? Come make some noise with us!

**Comment by whatevergeek** [comment]
as discussed in the channel... in some of our uke jam events in singapore, we just browse through a song book... and if anyone is familiar with the song... we just jam it... chords/lyrics are flashed on screen.... sometimes we use this songbook: https://ukulelewednesdays.com/songbook/ anyway, adding here for reference... feel free to let me know if there's anything i can help :-) (i'm bringing my 1/2 guitar or ukulele to the camp)

**Comment by AnnaGerber** [comment]
Thanks to everyone who took part in the jam!

**Comment by whatevergeek** [comment]
Thank you @AnnaGerber for organizing this :-)
