### ISSUE TITLE
Announce speakers

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#59]
*

**Comment by andrew-stirling** [comment]
Any timeline available on this? Need to get sign-off to purchase tickets.

**Comment by AshKyd** [comment]
@andrew-stirling No, we're still waiting for folks to confirm, but we have a couple of talks on the site already http://ix.campjs.com/speakers/

**Comment by AshKyd** [comment]
@andrew-stirling if you've signed up for emails on the site you would have just got an announcement. Otherwise they're on the site 👍
