### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-ix#6]
Looking for some help with the budget. Just a spreadsheet will do.

Last year's receipts were all kept and can be found https://github.com/campjs/campjs-viii/pulls?q=is%3Apr+is%3Aclosed+assignee%3ADamonOehlman which is a good starting place.

This venue is a bit cheaper at $195 per person including meals. The maximum capacity is 150 people which I expect to hit or come close to.

**Comment by gupta-kartik** [comment]
While preparing for the sponsorship package, I crunched the numbers from last year's reciepts to get a ballpark for this year. Details in excel sheet
[Budget-2017.xlsx](https://github.com/campjs/campjs-ix/files/1736890/Budget-2017.xlsx)
