### ISSUE TITLE
How do folks bring their family to CampJS

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#72]
As per #70.

Do the number of beds map 1:1 to the number of tickets? As in, do we lose out on a regular priced ticket for each child we add? What's a fair price for this?

**Comment by AshKyd** [comment]
@garrows what happened with this last time?

**Comment by MauriceButler** [comment]
This is the first time families have been offered at Koonjewarre. 

As far as private rooms there are 7 (possibly 8) rooms that have 8 bunks in them and a private bathroom. At least 1 of these is usually the dedicated female dorm.

Might be worth a call to Koonjewarre as I think they do have some smaller private rooms that might be better for families but I don't think they have been offered to us previously.

How to price that (fairly) as you say is going to be the hard one as thats potential 8 full priced tickets.

@garrows could probably confirm but I think in Melbourne the family tickets sold were just day passes and they had alternate accommodation?

As a seperate point, day passes were something requested last time we were at Koonjewarre, as it is close enough for some that they would prefer to sleep at home / alternative accommodation.
