### ISSUE TITLE
Stickers and Swag

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#74]
1. - [ ] Stickers with the logo?
2. - [ ] Iron-on Patches?
3. - [ ] Tees?
4. - [ ] Blankets?
5. - [ ] Space copters?

Please let me know your thoughts below. What's the official swag of CampJS?

**Comment by gupta-kartik** [comment]
NB: Sticker Mule

**Comment by AnnaGerber** [comment]
I thought we were going with badges as swag? See discussion on #19

**Comment by gupta-kartik** [comment]
We are. I ordered a limited number of stickers due to popular demand.
