### ISSUE TITLE
Subtract speakers for Tito numbers

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#76]

**Comment by gupta-kartik** [comment]
Give Nathan a ticket - through promo code

**Comment by gupta-kartik** [comment]
We have 10 speakers? @AshKyd

**Comment by AshKyd** [comment]
We have 11 tickets we need to send out, including workshops. The _CampJS IX 2018 - Call for Papers (Responses)_ sheet in the organization lists who these folks are. I've yet to get them all up on the site.
