### ISSUE TITLE
Code in the dark

### ISSUE THREAD

**Issue by gupta-kartik** [campjs/campjs-ix#78]

**Comment by loklaan** [comment]
👋 

Hey folks!

I've had a lot of fun at the "evening/after-talk" events at CampJS in the past. I thought it might be fun to pursue a html/css competition for camp IX: Code in the Dark!

# What is [Code in the Dark](http://codeinthedark.com)

_[Code in the Dark](http://codeinthedark.com) is a front-end (HTML, CSS) competition, originating from [Tictail](https://tictail.com), where each contestant compete to implement a website design given only a screenshot. The catch is that no previews of the results are allowed during the implementation, and no measuring tools can be used. The winner is decided by the audience._

_During the competition, the contestants have to use our custom editor for Code in the Dark, which [you can try out here](http://codeinthedark.com/editor)._

[...read more on the official github](https://github.com/codeinthedark/codeinthedark.github.io/blob/master/README.md)

It's basically a really fun "frontend hack" competition. DJ'd beats and lights are happening, everyone feels pretty rockstar, and it's short (1-2hrs)!

# Hosting a Code in the Dark inside CampJS

The "Code in the Dark" event is open sourced under a BSD 3 license. CampJS can use it (the name "Code in the Dark") as long as we've made a PR on their official github repo that states our interest, and also that we link back to the offical site from somewhere on [campjs.com](http://ix.campjs.com/).

Not saying we should do this, but if we want to drop "Code in the Dark" for another bespoke name, then we can skip the above steps.

The other things to consider when hosting are:

* [ ] The mock websites (challenges) that each round must recreate in html/css
* [ ] How many rounds we'd expect to host
* [ ] The max "contestants" we'd facilitate (4-6 is a good number?)
* Displaying contestant screens (the code!)
	* Projector (behind the contestants)  
	  _I reckon it's fine that contestants use their own laptop displays_
		* [ ] 4-way hdmi splitter costs ~$60 iirc, but likely be able to borrow some from community / companies
	* Individual screens (Used by the contestant, could be viewed by milling behind the contestants)  
	  _This is the lofi-solution, but a positive is it encourages the contestants & viewers to be fairly close (vibe)_
* [ ] Estimates for hiring lights  
  _Cool lighting seems to be a constant at CampJS - is there someone that always brings their kit along or something?_
* [ ] Sign-up & voting app  
  _Because of unreliable internet at the camp, it might be better to write a new webapp that uses SSB._
* [ ] Setup on the day
  1. Can contestants show their codes?
  2. Are all of the round challenges on 4-6 seperate usb sticks / the network for easy copying?
  3. Are the lights working?
  4. Is the signup & voting systems working?
  5. Do we have a (volunteer) MC?
  6. Do we have a (volunteer) DJ?
  7. Can we adjust the tables (in the dining hall) to allow for space?

**Comment by AshKyd** [comment]
I can bring some Lifx bulbs to set the scene if nobody has anything better.

Also at this rate I doubt we'll have much budget to throw at it, so it might have to be a little more home-grown.

**Comment by margalit** [comment]
I can bring three more Lifx bulbs to the party—this sounds like fun!

**Comment by loklaan** [comment]
Cheers @margalit @AshKyd - these are good for ambience! Bring 'em for sure.

I'll look into light hire / borrow as well, in an effort to try and top the lighting off with some line-strobes etc.

**Comment by AnnaGerber** [comment]
I have many metres of individually addressable WS2812b super bright RGB LED light strips as well as a pixel matrix (can be programmed to display scrolling text, pixel art etc) that I could bring to contribute to the lighting
