### ISSUE TITLE
Communications + volunteers for airport pickup

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#82]
We need to:

* work out who's flying in, and when
* find 2x volunteers to be at the airport for the early and late pickup
* communicate with attendees what's happening

**Comment by thissophie** [comment]
I arrive at Gold Coast airport @  12:30pm, which I think is a couple of hours before the early bus - so I’m happy to help out with that.

**Comment by gupta-kartik** [comment]
@thepatrick thank you so much! 

Can I contact you using the contact details you registered for the ticket to discuss the finer details?

**Comment by gupta-kartik** [comment]
Now we just need a second volunteer for the later bus

**Comment by thepatrick** [comment]
@gupta

**Comment by thissophie** [comment]
@gupta-kartik yep. I'm also on slack (as `patrick`).

**Comment by gupta-kartik** [comment]
Anai is doing the other one
