### ISSUE TITLE
Allocate cabins according to preferences

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#83]
Tally accommodation preferences on ti.to, then use that to divide up the cabins accordingly.

These will need to be labelled appropriately, which can be done in #40.

**Comment by gupta-kartik** [comment]
We'll do final allocations on the day using signs on the door like last time. 

So far after 71 tickets registered and 76 bought:

- [ ] Females Only - Dorm 
- [ ] Mix - Dorm
- [ ] Snorers - Dorm
- [ ] Tent/Camping - Outside
- [ ] Family Room - Family Unit
- [ ] Own 
- [ ] Unknown  

![image](https://user-images.githubusercontent.com/205256/43195258-d8ce5898-9047-11e8-8580-acd28a757cbf.png)

Original map here
http://koonjewarre.com/FORMS/KOONJEWARRE_INFORMATION.pdf
