### ISSUE TITLE
Update sponsors on the website

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#84]

**Comment by AshKyd** [comment]
@gupta-kartik can you put together a spreadsheet or something for these ones? Thaaaaanks! 🎉

**Comment by gupta-kartik** [comment]
@AshKyd 


Type | Company Name
-- | --
Platinum | Credit Sense
Platinum | PCCW Global
Gold | Culture Amp
Diversity and Coffee | Lookahead Search
Network | Funcaptcha
Drinks | REX
Meal | Bloqspace

**Comment by gupta-kartik** [comment]
[Sponsors Logos.zip](https://github.com/campjs/campjs-ix/files/2239592/Sponsors.Logos.zip)
