### ISSUE TITLE
Refresh the sponsorship info

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-ix#9]
https://github.com/campjs/campjs-viii/blob/master/org/sponsorship/campjs_viii_sponsor_plus.pdf

1. the code of conduct has been updated
2. The speakers might need to be refreshed
3. Could be less flashy. Bit hard to read.

**Comment by AshKyd** [comment]
I've replaced the existing PDF with a printable HTML solution. Hopefully it will be easier to update & brand in future. 

https://github.com/campjs/brochure-sponsorship-info
There's a preview here: https://blissful-lovelace-c1358e.netlify.com/

**Comment by AshKyd** [comment]
Things to consider:

1. This is a LOT of sponsors we need. Should we combine the 2x bus sponsors
1. This doesn't include childcare or captions
